name: build_and_test

env:
  CONAN_REF: "platform-inspector/0.0.2"
  CONAN_USERNAME: "conan-burrito"
  CONAN_UPLOAD: "https://conan.yobasoft.de"
  CONAN_UPLOAD_RETRY: 50
  CONAN_STABLE_BRANCH_PATTERN: "release/*"
  CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Checkout profiles
        uses: actions/checkout@v2
        with:
          repository: conan-burrito/profiles
          path: profiles
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan conan_package_tools
            conan remote add conan-burrito ${{ env.CONAN_UPLOAD }}
            conan user -r conan-burrito -p "${{ env.CONAN_PASSWORD }}" ${{ secrets.CONAN_LOGIN_USERNAME }}
            conan config install ${{ github.workspace }}/profiles/settings.yml
      - name: Export recipe
        run: |
            conan export . ${{ env.CONAN_REF }}@${{ env.CONAN_USERNAME }}/stable
      - name: Build a native application
        run: |
            cd test
            conan create . inspector-test/0.1
      - name: Build WASM
        if: ${{ ! startsWith(matrix.os, 'windows') }}
        run: |
            cd test
            conan create -pr ${{ github.workspace }}/profiles/emscripten . inspector-test/0.1
      - name: Build an Android application
        run: |
            cd test
            conan create -pr ${{ github.workspace }}/profiles/android . inspector-test/0.1
      - name: Build an iOS application
        if: startsWith(matrix.os, 'macos')
        run: |
            cd test
            conan create -pr ${{ github.workspace }}/profiles/ios . inspector-test/0.1
      - name: Upload the recipe
        if: startsWith(matrix.os, 'macos')
        run: conan upload -r conan-burrito ${{ env.CONAN_REF }}
